version: '3'

services:
  authelia:
    image: authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - /mnt/authelia/config:/config
      - /mnt/nginx/data:/nginx/
    ports:
      - "9091:9091"
    network_mode: host